![imagen](./img/ejercicios.png)

# Ejercicio SQL
Para este ejercicio usaremos una base de datos de Pokemon. **Asegúrante que tienes el CSV "pokemon.csv" en la misma carpeta donde está este Notebook**. Realiza los siguientes apartados:

1. Obten una tabla con todos los campos
2. Obten una tabla con los campos "Name", "Type 1", "Type 2"
3. Obten la misma tabla que el apartado anterior, pero en este caso renombrando los campos al castellano.
4. ¿Cuales son todos los "Type 1" diferentes?
5. ¿Cuales son todos los "Type 1" y "Type 2" diferentes?
6. ¿Cuáles son los pokemon de agua? "Type 1" = "Water"
7. Obtén una tabla con los pokemon legendarios
8. Obtén una tabla con los pokemon legendarios de fuego ("Type 1" = "Fire")
9. Obtén una tabla con los pokemon cuyo nombre empieze por "W" y tenga una defensa mayor de 100 puntos
10. Saca una tabla con los pokemon de la primera generación, que NO sean "Type 1" = "Psychic" y tengan una velocidad superior a 130
11. ¿Cuál es el pokemon con el ataque más alto?
12. ¿Cuál es la media de la defensa de todos los pokemon?
13. ¿Cuál es la media de la defensa por generación?
14. Calcula el máximo HP por "Type 1"

**NOTA**: se recomienda añadir un `LIMIT 5` en la mayoría de apartados para evitar grandes outputs de las queries.

In [1]:
# Importamos paquetes
import pandas as pd
import sqlite3
cnx = sqlite3.connect(':memory:')

# Importamos datos de un CSV
df = pd.read_csv('pokemon.csv')
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [2]:
# Pasamos el DataFrame de Pandas a SQL
df.to_sql('pokemon', con=cnx, if_exists='append', index=False)

# Definimos la función para hacer queries.
def sql_query(query):
    return pd.read_sql(query, cnx)

In [3]:
# 1. Obten una tabla con todos los campos
query = '''
select * from pokemon;
'''

sql_query(query)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,0
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,0
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,0
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,0
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,1
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,1
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,1
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,1
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,1

In [33]:
# 2. Obten una tabla con los campos "Name", "Type 1", "Type 2"
query = '''
select name, "type 1", "type 2"
 from pokemon limit 5;
'''

sql_query(query)

                    Name Type 1  Type 2
0              Bulbasaur  Grass  Poison
1                Ivysaur  Grass  Poison
2               Venusaur  Grass  Poison
3  VenusaurMega Venusaur  Grass  Poison
4             Charmander   Fire     NaN

In [34]:
# 3. Obten la misma tabla que el apartado anterior, pero en este caso renombrando los campos al castellano.
query = '''
select name Nombre, "type 1" tipo_1, "type 2" tipo_2 from pokemon;
'''

sql_query(query)

                    Nombre   tipo_1  tipo_2
0                Bulbasaur    Grass  Poison
1                  Ivysaur    Grass  Poison
2                 Venusaur    Grass  Poison
3    VenusaurMega Venusaur    Grass  Poison
4               Charmander     Fire     NaN
..                     ...      ...     ...
795                Diancie     Rock   Fairy
796    DiancieMega Diancie     Rock   Fairy
797    HoopaHoopa Confined  Psychic   Ghost
798     HoopaHoopa Unbound  Psychic    Dark
799              Volcanion     Fire   Water

[800 rows x 3 columns]

In [42]:
# 4. ¿Cuales son todos los "Type 1" diferentes?
query = '''
select distinct "type 1" from pokemon;
'''

sql_query(query)

      Type 1
0      Grass
1       Fire
2      Water
3        Bug
4     Normal
5     Poison
6   Electric
7     Ground
8      Fairy
9   Fighting
10   Psychic
11      Rock
12     Ghost
13       Ice
14    Dragon
15      Dark
16     Steel
17    Flying

In [39]:
# 5. ¿Cuales son todos los "Type 1" y "Type 2" diferentes?
query = '''
select distinct "type 1", "type 2" from pokemon order by "type 1" asc;
'''

sql_query(query)

    Type 1  Type 2
0      Bug     NaN
1      Bug  Flying
2      Bug  Poison
3      Bug   Grass
4      Bug   Steel
..     ...     ...
149  Water    Rock
150  Water  Dragon
151  Water   Grass
152  Water   Steel
153  Water   Ghost

[154 rows x 2 columns]

In [ ]:
# 6. ¿Cuáles son los pokemon de agua? "Type 1" = "Water"
query = '''
    select name from pokemon where "type 1" == "Water" llimit 5;
'''

sql_query(query)

                        Name
0                   Squirtle
1                  Wartortle
2                  Blastoise
3    BlastoiseMega Blastoise
4                    Psyduck
..                       ...
107                  Froakie
108                Frogadier
109                 Greninja
110                Clauncher
111                Clawitzer

[112 rows x 1 columns]

In [43]:
# 7. Obtén una tabla con los pokemon legendarios
query = '''
select * from pokemon where legendary is true;
'''

sql_query(query)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,144,Articuno,Ice,Flying,580,90,85,100,95,125,85,1,1
1,145,Zapdos,Electric,Flying,580,90,90,85,125,90,100,1,1
2,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,1
3,150,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,1
4,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,1
61,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,1
62,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,1
63,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,1
64,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,1

In [ ]:
# 8. Obtén una tabla con los pokemon legendarios de fuego ("Type 1" = "Fire")
query = '''
    select * from pokemon where legendary is true and "type 1" = "Fire";
'''

sql_query(query)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,1
1,244,Entei,Fire,NaN,580,115,115,85,90,75,100,2,1
2,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,1
3,485,Heatran,Fire,Steel,600,91,90,106,130,106,77,4,1
4,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,1

In [ ]:
# 9. Obtén una tabla con los pokemon cuyo nombre empieze por "W" y tenga una defensa mayor de 100 puntos
query = '''
    select * from pokemon where name like "W%";
'''

sql_query(query)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,0
1,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,0
2,40,Wigglytuff,Normal,Fairy,435,140,70,45,85,50,45,1,0
3,70,Weepinbell,Grass,Poison,390,65,90,50,85,45,55,1,0
4,110,Weezing,Poison,NaN,490,65,90,120,85,70,60,1,0
5,194,Wooper,Water,Ground,210,55,45,45,25,25,15,2,0
6,202,Wobbuffet,Psychic,NaN,405,190,33,58,33,58,33,2,0
7,265,Wurmple,Bug,NaN,195,45,45,35,20,30,20,3,0
8,278,Wingull,Water,Flying,270,40,30,30,55,30,85,3,0
9,293,Whismur,Normal,NaN,240,64,51,23,51,23,28,3,0
10,320,Wailmer,Water,NaN,400,130,70,35,70,35,60,3,0
11,321,Wailord,Water,NaN,500,170,90,45,90,45,60,3,0
12,340,Whiscash,Water,Ground,468,110,78,73,76,71,60,3,0
13,360,Wynaut,Psychic,NaN,260,95,23,48,23,48,23,3,0
14,365,Walrein,Ice,Water,530,110,80,90,95,90,65,3,0
15,413,WormadamPlant Cloak,Bug,Grass,424,60,59,85,79,105,36,4,0
16,413,WormadamSandy Cloak,Bug,Ground,424,60,79,105,59,85,36,4,0
17,413,WormadamTrash Cloak,Bug,Steel,424,60,69,95,69,95,36,4,0
18,461,Weavile,Dark,Ice,510,70,120,65,45,85,125,4,0
19,505,Watchog,Normal,NaN,420,60,85,69,60,69,77,5,0
20,527,Woobat,Psychic,Flying,313,55,45,43,55,43,72,5,0
21,544,Whirlipede,Bug,Poison,360,40,55,99,40,79,47,5,0
22,547,Whimsicott,Grass,Fairy,480,60,67,85,77,75,116,5,0

In [ ]:
# 10. Saca una tabla con los pokemon de la primera generación, que NO sean "Type 1" = "Psychic" y tengan una velocidad superior a 130
query = '''
    select * from pokemon where (generation == 1 and not "type 1" = "Psychic") and speed > 130;
'''

sql_query(query)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,0
1,101,Electrode,Electric,NaN,480,60,50,70,80,80,140,1,0
2,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,0

In [4]:
# 11. ¿Cuál es el pokemon con el ataque más alto?
query = '''
    select name, max(attack) from pokemon;
'''

sql_query(query)

                  Name  max(attack)
0  MewtwoMega Mewtwo X          190

In [57]:
# 12. ¿Cuál es la media de la defensa de todos los pokemon?
query = '''
select avg(defense) MediaDefensa from pokemon;
'''

sql_query(query)

   MediaDefensa
0       73.8425

In [60]:
# 13. ¿Cuál es la media de la defensa por generación?
query = '''
select generation, avg(defense) MediaDefensa from pokemon group by generation;
'''

sql_query(query)

   Generation  MediaDefensa
0           1     70.861446
1           2     73.386792
2           3     74.100000
3           4     78.132231
4           5     72.327273
5           6     76.682927

In [64]:
# Apartado 14. Calcula el máximo HP por "Type 1"
query = '''
    select "type 1", hp from pokemon group by "type 1";
'''

sql_query(query)

      Type 1  HP
0        Bug  45
1       Dark  95
2     Dragon  41
3   Electric  35
4      Fairy  70
5   Fighting  40
6       Fire  39
7     Flying  79
8      Ghost  30
9      Grass  45
10    Ground  50
11       Ice  65
12    Normal  40
13    Poison  35
14   Psychic  25
15      Rock  40
16     Steel  75
17     Water  44